spring:
  application:
    name: earlybird
  profiles:
    active: ${SPRING_ACTIVE_PROFILE}
  jwt:
    secret: ${JWT_SECRET}

fcm:
  service-account-file: key/firebase_admin_sdk_private_key.json
  project-id: ${FCM_PROJECT_ID}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}